name = "swankyb-pages"

# Cloudflare Pages config - keep build command and set output dir
compatibility_date = "2025-10-13"
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "swankyboyz_d1_final"
database_id = "fb8ab815-af3a-4102-ab39-aeabcb829008"

# Build configuration is not supported in wrangler.toml for Pages
# Build command should be configured in Cloudflare Pages dashboard or package.json
# [build]
# command = "npm run build"

# Environment variables 
[vars]
# JWT authentication secret for admin endpoints
JWT_SECRET = "your-super-secret-jwt-key-change-in-production-12345"
# Site configuration
SITE_URL = "https://swankyboyz.com"
