name = "swankyb-pages"
account_id = "43f14f26801fb2389382fa084e3442e6"
zone_id = "5b509f42c17a19c3970cc79432a88ac5"

# Cloudflare Pages config - keep build command and set output dir
compatibility_date = "2025-10-13"
pages_build_output_dir = "dist"

[pages]
project_name = "swankyb-pages"

[build]
command = "npm run build"

# Environment variables for Supabase (Bolt Database)
[vars]
VITE_BOLT_DATABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1d2N6d3BmbnN3d2N0dW12cXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1Mzg4ODMsImV4cCI6MjA3NTExNDg4M30.EGziTHFcFPQprqmSrvvfxzEEHY2HVuknezkpGidd3UA"
VITE_BOLT_DATABASE_URL = "https://wuwczwpfnswwctumvqsq.supabase.co"
