# NOTE: Do NOT commit secrets (account_id, API tokens) to git.
# Fill `account_id` locally or in CI secrets before deploying.
account_id = ""
project_name = "swankyB"

[build]
	command = "npm run build"
	directory = "./dist"

[functions]
	directory = "./functions"

# If you need to set environment variables for Pages/Functions,
# add them in the Cloudflare Dashboard (Pages -> Settings -> Environment variables)
# or inject them at CI time. Do not store secrets in this repo.
