# NOTE: Do NOT commit secrets (account_id, API tokens) to git.
# Fill `account_id` locally or in CI secrets before deploying.
name = "swanky-boyz"
account_id = "43f14f26801fb2389382fa084e3442e6"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB" # Available in Functions as context.env.DB
database_name = "swankyb_content"
database_id = "bfc16265-30bd-4bcf-8a72-f2a5a5baf61a"

# If you need to set environment variables for Pages/Functions,
# add them in the Cloudflare Dashboard (Pages -> Settings -> Environment variables)
# or inject them at CI time. Do not store secrets in this repo.
