name = "swankyb-pages"
compatibility_date = "2025-10-13"

[[d1_databases]]
binding = "DB"
database_name = "swankyboyz_db"
database_id = "fb8ab815-af3a-4102-ab39-aeabcb829008"

# Build configuration is not supported in wrangler.toml for Pages
# Build command should be configured in Cloudflare Pages dashboard or package.json