name = "swankyboyz"
main = "dist"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "swankyboyz_db"
database_id = "your-d1-database-id"

[site]
bucket = "./dist"

# Environment variables 
[vars]
# JWT authentication secret for admin endpoints
JWT_SECRET = "your-super-secret-jwt-key-change-in-production-12345"
# Site configuration
SITE_URL = "https://swankyboyz.com"
