name: Sync Content from Google Sheets

on:
  schedule:
    # Every Monday at 2AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch: # Allow manual triggering
  
env:
  NODE_VERSION: '22.x'

jobs:
  sync-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Google Sheets credentials
        run: |
          mkdir -p scripts
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > scripts/credentials.json
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          
      - name: Sync content from Google Sheets
        run: npm run sync
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          
      - name: Validate images
        run: npm run validate-images
        
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "🤖 Weekly content sync from Google Sheets [skip ci]"
          git push
          
      - name: No changes detected
        if: steps.git-check.outputs.changes != 'true'
        run: echo "No changes detected in content sync"